services:
  mobile-api:
    image: mobile-api
    build:
      context: .
      dockerfile: mobile-api/Dockerfile
    restart: always
    ports:
        - "8080:8080"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Server=db;Database=YourDatabase;User Id=sa;Password=YourStrong@Passw0rd;Trust Server Certificate=True;
        - ASPNETCORE_HTTP_PORT=80
    depends_on:
      - db
    volumes:
      - ./mobile-api/wwwroot:/app/wwwroot:rw
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
